services:
  app:
    container_name: test-github-actions
    image: ghcr.io/${GIT_REPOSITORY}:${GIT_COMMIT_HASH:-latest}
    ports:
      - "8502:8501"
    secrets:
      - secret-name
    environment:
      - SECRET_NAME=/run/secrets/secret-name
    deploy:
      update_config:
        order: start-first

secrets:
  secret-name:
    external: true
