name: Deploy to VPS

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run_pull:
    name: run pullzed
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          -  name: connect and pull
            run: |
              ssh -t ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
                cd ${{ secrets.WORK_DIR }}
                git checkout ${{ secrets.MAIN_BRANCH }}
                git pull
                touch hello.txt
                exit
              EOF
      - name: cleanup
        run: rm -rf ~/.ssh
